(async()=>{
  'use strict';
  const A=Atlas,$=s=>document.querySelector(s),state=A.state;
  try{const mode=localStorage.getItem('heritage-atlas-timeline-mode');if(['bands','flow'].includes(mode))state.timelineMode=mode;}catch{}
  const physicsKey='heritage-atlas-network-physics-v2',physicsDefaults={distance:320,repulsion:520,labelScale:100};
  A.networkPhysics={...physicsDefaults};
  try{const saved=JSON.parse(localStorage.getItem(physicsKey));if(saved){if(Number.isFinite(saved.distance)&&saved.distance>=100&&saved.distance<=420)A.networkPhysics.distance=saved.distance;if(Number.isFinite(saved.repulsion)&&saved.repulsion>=80&&saved.repulsion<=850)A.networkPhysics.repulsion=saved.repulsion;if(Number.isFinite(saved.labelScale)&&saved.labelScale>=80&&saved.labelScale<=140)A.networkPhysics.labelScale=saved.labelScale;}}catch{}
  const syncPhysicsControls=()=>{$('#network-spacing').value=A.networkPhysics.distance;$('#network-repulsion').value=A.networkPhysics.repulsion;$('#network-text-scale').value=A.networkPhysics.labelScale;$('#network-spacing-value').value=String(A.networkPhysics.distance);$('#network-repulsion-value').value=String(A.networkPhysics.repulsion);$('#network-text-scale-value').value=A.networkPhysics.labelScale+'%';};
  const viewInfo={timeline:['01 / TOPIC × TIME MAP','Ideas and documents across time','X: year · Y: working topic · Title and author/organisation appear beside each dot · Click for the full record.'],cluster:['02 / TOPIC CLUSTERS','Documents grouped by shared codes','A record appears in every selected cluster it matches. Click any item to open its full record.'],network:['03 / RELATIONSHIP GRAPH','Explore connections','Open force-directed graph · Hover a node to trace links · Drag to explore and scroll to zoom.'],matrix:['04 / RESEARCH LIBRARY','Research library','Sort columns or open a record to read source notes.']};
  A.render=()=>{
    document.body.classList.toggle('flow-active',state.view==='timeline'&&state.timelineMode==='flow');
    document.body.classList.toggle('network-active',state.view==='network');A.sim?.stop();A.sim=null;A.fitNetwork=null;A.updateNetworkPhysics=null;A.updateNetworkLabelScale=null;A.hideTooltip();A.visible=A.filtered();$('#chart').replaceChildren();$('#chart').classList.remove('timeline-chart','network-chart','flow-chart');$('#chart').style.removeProperty('overflow-y');$('#chart').style.setProperty('--dot-scale',String(state.dotScale||1));
    const info=state.view==='timeline'&&state.timelineMode==='flow'?['01 / OVERLAPPING THEMES × TIME','A landscape of shared ideas','X: year · Organic envelopes: working themes · Overlap: shared subject matter · Click a dot for source notes.']:viewInfo[state.view];$('#view-number').textContent='VIEW '+info[0];$('#view-title').textContent=info[1];$('#view-hint').textContent=info[2];$('#result-count').textContent=`${A.visible.length} / ${A.records.length} entries`;
    document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===state.view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});
    $('#timeline-control').hidden=state.view!=='timeline';document.querySelectorAll('[data-timeline-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.timelineMode===state.timelineMode)));$('#cluster-control').hidden=state.view!=='cluster';$('#network-control').hidden=state.view!=='network';$('#dot-scale-control').hidden=state.view!=='timeline';$('#dot-scale').value=Math.round((state.dotScale||1)*100);$('#dot-scale-value').value=$('#dot-scale').value+'%';syncPhysicsControls();
    const count=Object.values(state.filters).reduce((n,set)=>n+set.size,0)+(state.minYear!==''?1:0)+(state.maxYear!==''?1:0);$('#filter-count').textContent=count||'＋';
    const legend=$('#legend');legend.replaceChildren();for(const [value,color]of Object.entries(A.typeColors)){const item=A.el('span','legend-item'),swatch=A.el('i','swatch');swatch.style.setProperty('--swatch',color);item.append(swatch,document.createTextNode(value));legend.append(item);}legend.append(A.el('span','legend-note','Size: provisional theoretical contribution · Practice cases are unscored · Dashed: reading pending'));
    if(!A.visible.length){const empty=A.el('div','empty-state');empty.append(A.el('h3','','No matching entries'),A.el('p','','没有符合条件的条目，请调整搜索或筛选。'));const reset=A.el('button','text-button','清空搜索与筛选');reset.onclick=A.reset;empty.append(reset);$('#chart').append(empty);return;}
    if(typeof d3==='undefined'&&state.view==='network'){$('#chart').append(A.el('p','error','D3 unavailable; Timeline and Library remain available.'));return;}
    A[state.view](A.visible);
  };
  A.reset=()=>{Object.assign(state,{query:'',filters:{},minYear:'',maxYear:'',lens:'stream',cluster:'topic_memberships',relation:'',sort:'year',direction:1,dotScale:1});$('#search').value='';$('#cluster-by').value='topic_memberships';$('#relation-type').value='';A.buildFilters();A.render();};
  A.buildFilters=()=>{
    const root=$('#filter-fields');root.replaceChildren();const year=A.el('fieldset');year.append(A.el('legend','','Year / 年份'));const inputs=A.el('div','year-fields');for(const [key,label]of [['minYear','起始年份'],['maxYear','结束年份']]){const l=A.el('label','',label),input=A.el('input');input.type='number';input.min=0;input.max=9999;input.value=state[key];input.placeholder=key==='minYear'?'1930':String(new Date().getFullYear());input.oninput=()=>{state[key]=input.value;A.render();};l.append(input);inputs.append(l);}year.append(inputs);root.append(year);
    const fields={topic_memberships:'Flow themes / 多主题归属',interpretive_setting:'Interpretive setting / 阐释情境',type:'Document Type',document_nature:'Document nature / 文件性质',paradigm:'Paradigm',themes:'Theme',concepts:'Key Concepts',heritage_conception:'Heritage Conception',interpretation_model:'Interpretation Model',authority_structure:'Authority',public_role:'Public Role',narrative_structure:'Narrative',media:'Media',public_actions:'Public Actions'};
    for(const [key,label]of Object.entries(fields)){const group=A.el('fieldset');group.append(A.el('legend','',label));if(key==='interpretive_setting')group.append(A.el('p','small','On-site = 现场 · Off-site = 场外 · Both = 两者兼有。筛选现场或场外时也包含 Both；情境与数字媒介分别编码。'));const values=[...new Set([...A.arr(A.data.vocabulary[key]),...A.categories(key)])].sort();for(const value of values){const l=A.el('label','check-option'),input=A.el('input');input.type='checkbox';input.checked=state.filters[key]?.has(String(value))||false;input.onchange=()=>{state.filters[key]??=new Set();input.checked?state.filters[key].add(String(value)):state.filters[key].delete(String(value));A.render();};l.append(input,document.createTextNode(String(value)));group.append(l);}root.append(group);}
  };
  A.load=(raw,source)=>{A.setData(raw);A.reset();$('#data-status').classList.remove('error');$('#data-status').textContent=`${source} · ${A.data.meta.is_sample?'示例数据库：摘要、编码与关系待原文校核。':'已加载知识库。'}`;};
  for(const [key,label]of Object.entries(A.fields)){const o=A.el('option','',label);o.value=key;$('#cluster-by').append(o);}
  for(const type of A.relationTypes){const o=A.el('option','',type);o.value=type;$('#relation-type').append(o);}
  $('#cluster-by').onchange=e=>{state.cluster=e.target.value;A.render();};$('#relation-type').onchange=e=>{state.relation=e.target.value;A.render();};
  const persistPhysics=()=>{syncPhysicsControls();try{localStorage.setItem(physicsKey,JSON.stringify(A.networkPhysics));}catch{}};
  const updatePhysics=()=>{A.networkPhysics.distance=Number($('#network-spacing').value);A.networkPhysics.repulsion=Number($('#network-repulsion').value);persistPhysics();A.updateNetworkPhysics?.();};
  const updateLabelScale=()=>{A.networkPhysics.labelScale=Number($('#network-text-scale').value);persistPhysics();A.updateNetworkLabelScale?.();};
  $('#network-spacing').oninput=updatePhysics;$('#network-repulsion').oninput=updatePhysics;$('#network-text-scale').oninput=updateLabelScale;
  $('#network-defaults').onclick=()=>{$('#network-spacing').value=physicsDefaults.distance;$('#network-repulsion').value=physicsDefaults.repulsion;$('#network-text-scale').value=physicsDefaults.labelScale;A.networkPhysics={...physicsDefaults};persistPhysics();A.updateNetworkPhysics?.();A.updateNetworkLabelScale?.();};
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;A.render();});
  document.querySelectorAll('[data-timeline-mode]').forEach(b=>b.onclick=()=>{state.timelineMode=b.dataset.timelineMode;try{localStorage.setItem('heritage-atlas-timeline-mode',state.timelineMode);}catch{}A.render();});
  $('#search').oninput=e=>{state.query=e.target.value;A.render();};$('#reset').onclick=A.reset;$('#dot-scale').oninput=e=>{state.dotScale=Number(e.target.value)/100;$('#dot-scale-value').value=e.target.value+'%';$('#chart').style.setProperty('--dot-scale',String(state.dotScale));};
  let resizeFrame=0;window.addEventListener('resize',()=>{if(state.view==='timeline'||state.view==='network'){cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>A.render());}});
  $('#filters-button').onclick=()=>{$('#filter-dialog').showModal();$('#filters-button').setAttribute('aria-expanded','true');};
  $('#filter-dialog').addEventListener('close',()=>$('#filters-button').setAttribute('aria-expanded','false'));
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
  $('#clear-filters').onclick=()=>{state.filters={};state.minYear='';state.maxYear='';A.buildFilters();A.render();};
  $('#json-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const raw=JSON.parse(await f.text());A.load(raw,`本地文件：${f.name}`);A.editor.imported();}catch(err){$('#data-status').textContent='未替换当前数据：'+err.message;$('#data-status').classList.add('error');}e.target.value='';};
  try{if(location.protocol==='file:'){A.load(window.ATLAS_SNAPSHOT,'离线预览快照 · 修改 JSON 后请点“打开本地 JSON”');}else{const response=await fetch('data/knowledge.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);A.load(await response.json(),'knowledge.json');}}
  catch(err){$('#data-status').textContent='加载失败：'+err.message+'。请检查 JSON 或选择本地文件。';$('#data-status').classList.add('error');$('#chart').append(A.el('div','empty-state','知识库尚未加载；可通过右下方打开本地 JSON。'));}
  A.editor.init();A.editor.restore();
  // Optional progressive enhancement; ordinary browsers use the visible controls.
  if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'search_heritage_atlas',description:'Search the atlas and update its visible results.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(typeof input?.query!=='string')throw new Error('query must be a string');state.query=input.query;$('#search').value=input.query;A.render();return {entries:A.visible.map(({id,title,year})=>({id,title,year}))};}});}catch(err){console.info('Optional atlas tool unavailable:',err.message);}}
})();
