Atlas.openDetail=function(id){
  const A=Atlas,d=A.byId.get(id);if(!d)return;A.hideTooltip();
  const panel=document.querySelector('#detail-dialog'),root=document.querySelector('#detail-content');root.replaceChildren();
  root.append(A.el('div','entry-number',d.year_label||d.year||d.node_type.toUpperCase()));
  const title=A.el('h2','',d.title);title.id='detail-title';if(d.title_zh)title.append(A.el('span','',d.title_zh));root.append(title);
  const meta=A.el('dl','detail-meta');for(const [label,value]of [['Original title',d.title],['Author',A.text(d.author)],['Organisation',d.organization],['Node / Type',`${d.node_type.toUpperCase()}${d.type?' / '+d.type:''}`],['Paradigm',A.text(d.paradigm)],['Key concepts',A.text(d.concepts)],['Themes',A.text(d.themes)],['Heritage',A.text(d.heritage_conception)],['Interpretation',A.text(d.interpretation_model)],['Authority',A.text(d.authority_structure)],['Public role',A.text(d.public_role)],['Narrative',A.text(d.narrative_structure)],['Media',A.text(d.media)],['Public actions',A.text(d.public_actions)]]){meta.append(A.el('dt','',label),A.el('dd','',value||'—'));}root.append(meta);
  if(d.coding_status)root.append(A.el('p','small',d.coding_status));
  for(const [label,key]of [['WHAT DOES IT SAY? / 内容摘要','summary'],['WHAT CHANGED? / 理论转向','paradigm_shift'],['WHY DOES IT MATTER? / 研究意义','significance'],['PHD RELEVANCE / 博士研究关联','phd_relevance'],['MY NOTES / 阅读笔记','my_notes']]){const section=A.el('section','detail-section');section.append(A.el('h3','',label),A.el('p','',d[key]||'尚未添加'));root.append(section);}
  if(d.annotations?.length){const s=A.el('section','detail-section');s.append(A.el('h3','','ANNOTATIONS / 标注'));for(const a of d.annotations){s.append(A.el('p','',`${a.text||''}${a.page!=null?'（p. '+a.page+'）':''}`));}root.append(s);}
  const related=A.el('section','detail-section');related.append(A.el('h3','','RELATED NODES / 相关节点'));
  const relations=(d.relations||[]).map(r=>({...r,other:r.target,direction:'→'}));for(const n of A.byId.values())for(const r of n.relations||[])if(r.target===id)relations.push({...r,other:n.id,direction:'←'});
  if(!relations.length)related.append(A.el('p','small','尚未建立关系'));for(const r of relations){const other=A.byId.get(r.other);if(!other)continue;const b=A.el('button','related-button',`${r.direction} ${other.title}`);b.append(A.el('small','',`${r.type} · ${r.evidence||'未提供关系证据'}`));b.onclick=()=>A.openDetail(other.id);related.append(b);}root.append(related);
  const links=A.el('section','detail-section');links.append(A.el('h3','','SOURCE / PDF'));const holder=A.el('div','source-links');for(const [label,url,isPDF]of [['查看来源 ↗',d.source_url,false],['Open PDF ↗',d.pdf,true]]){const safe=A.safeURL(url,isPDF);if(safe){const a=A.el('a','',label);a.href=safe;a.target='_blank';a.rel='noopener noreferrer';holder.append(a);}else if(isPDF)holder.append(A.el('span','small',url?'PDF path unavailable':'PDF not added yet'));}links.append(holder);root.append(links);
  if(!panel.open)panel.showModal();panel.scrollTop=0;
};
