/* Browser draft editor and explicit GitHub Contents API publishing. */
Atlas.editor=(()=>{
  const A=Atlas,$=s=>document.querySelector(s);
  const key='heritage-atlas-draft-v1';
  const api='https://api.github.com/repos/Yueying-Zhang-99/heritage-interpretation-atlas/contents/data/knowledge.json';
  const tagFields={type:'条目类型',paradigm:'理论范式',themes:'主题',concepts:'关键概念',heritage_conception:'遗产观',interpretation_model:'阐释模式',authority_structure:'阐释权力',public_role:'公众角色',narrative_structure:'叙事结构',media:'媒介技术',public_actions:'公众行动'};
  const listFields=['author',...Object.keys(tagFields).filter(k=>k!=='type')];
  const simpleFields={id:'唯一 ID',title:'英文标题',title_zh:'中文标题',year:'年份',year_label:'年份显示',organization:'机构',summary:'内容摘要',paradigm_shift:'理论转向',significance:'研究意义',phd_relevance:'博士研究关联',my_notes:'阅读笔记',source_url:'来源网址',pdf:'PDF 路径或网址',coding_status:'编码状态'};
  let baseline=null,tab='entries',selected=null,editing=false;
  const clone=v=>JSON.parse(JSON.stringify(v));
  const status=(message,error=false)=>{const p=$('#editor-status');p.textContent=message;p.classList.toggle('error',error);};
  const field=(label,value='',kind='input')=>{const wrap=A.el('label','editor-field',label),el=A.el(kind);if(kind==='textarea')el.rows=3;else el.type='text';el.value=value??'';wrap.append(el);return [wrap,el];};
  const draft=()=>{try{localStorage.setItem(key,JSON.stringify({data:A.data,baseline}));status('草稿已保存在此浏览器；尚未发布。');$('#data-status').textContent='浏览器草稿 · 尚未发布到 GitHub';}catch(err){status('浏览器存储失败，请立即导出 JSON 备份：'+err.message,true);}};
  const refresh=()=>{A.setData(A.data);A.buildFilters();A.render();$('#total-count').textContent=String(A.records.length).padStart(2,'0');draw();draft();};
  const entries=()=>[...A.data.documents,...A.data.nodes];
  const makeButton=(label,fn,cls='outline-button')=>{const b=A.el('button',cls,label);b.type='button';b.onclick=fn;return b;};
  function draw(){const root=$('#editor-content');root.replaceChildren();$('#edit-entries-tab').classList.toggle('active',tab==='entries');$('#edit-labels-tab').classList.toggle('active',tab==='labels');if(tab==='labels')drawLabels(root);else if(editing)drawForm(root);else drawEntries(root);}
  function drawEntries(root){const actions=A.el('div','editor-row');actions.append(makeButton('＋ 新增条目',()=>{selected=null;editing=true;draw();},'solid-button'));root.append(actions);const list=A.el('div','editor-list');for(const d of entries()){const row=A.el('div','editor-list-item');row.append(A.el('span','',`${d.year_label||d.year||'—'} · ${d.title}${d.title_zh?' / '+d.title_zh:''}`),makeButton('编辑',()=>{selected=d.id;editing=true;draw();}));list.append(row);}root.append(list);}
  function drawForm(root){const existing=selected?A.byId.get(selected):null,form=A.el('form','editor-form');form.noValidate=true;
    const kindWrap=A.el('label','editor-field','条目类别'),kind=A.el('select');for(const [value,label]of [['document','文献 / 事件'],['person','人物'],['concept','概念 / 研究主题']]){const o=A.el('option','',label);o.value=value;kind.append(o);}kind.value=existing?.node_type||'document';kind.disabled=!!existing;kindWrap.append(kind);form.append(kindWrap);
    const streamWrap=A.el('label','editor-field','理论流'),stream=A.el('select');for(const [value,item]of Object.entries(A.streams)){const o=A.el('option','',`${value} · ${item.zh}`);o.value=value;stream.append(o);}stream.value=existing?.stream||'A';streamWrap.append(stream);form.append(streamWrap);
    const inputs={};for(const [name,label]of Object.entries(simpleFields)){const [wrap,input]=field(label,existing?.[name]??'',['summary','paradigm_shift','significance','phd_relevance','my_notes'].includes(name)?'textarea':'input');if(name==='id'&&existing)input.readOnly=true;if(name==='year')input.type='number';inputs[name]=input;form.append(wrap);}
    const typeWrap=A.el('label','editor-field','条目类型标签'),type=A.el('input');type.value=existing?.type||'';type.setAttribute('list','editor-type-options');const typeOptions=A.el('datalist');typeOptions.id='editor-type-options';for(const v of A.arr(A.data.vocabulary.type)){const o=A.el('option');o.value=v;typeOptions.append(o);}typeWrap.append(type,typeOptions);form.append(typeWrap);
    for(const name of listFields){const [wrap,input]=field(`${tagFields[name]||'作者'}（每行一个标签）`,A.arr(existing?.[name]).join('\n'),'textarea');inputs[name]=input;form.append(wrap);}
    for(const name of ['relations','annotations']){const [wrap,input]=field(`${name}（JSON 数组，高级）`,JSON.stringify(existing?.[name]||[],null,2),'textarea');inputs[name]=input;form.append(wrap);}
    const buttons=A.el('div','editor-actions');buttons.append(makeButton('返回列表',()=>{editing=false;draw();}),makeButton('保存到草稿',()=>{try{const d=existing?clone(existing):{};for(const [name,input]of Object.entries(inputs)){if(name==='relations'||name==='annotations'){d[name]=JSON.parse(input.value||'[]');if(!Array.isArray(d[name]))throw new Error(`${name} 必须是 JSON 数组`);}else if(listFields.includes(name))d[name]=input.value.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean);else d[name]=input.value.trim();}d.type=type.value.trim();d.stream=stream.value;d.node_type=kind.value;if(kind.value==='document'){if(d.year==='')throw new Error('文献条目必须填写年份');d.year=Number(d.year);}else if(d.year==='')delete d.year;else d.year=Number(d.year);const next=clone(A.data);const collection=kind.value==='document'?'documents':'nodes';const i=existing?next[collection].findIndex(x=>x.id===selected):-1;if(i<0)next[collection].push(d);else next[collection][i]=d;A.validate(next);A.setData(next);editing=false;refresh();}catch(err){status('无法保存条目：'+err.message,true);}},'solid-button'));if(existing)buttons.append(makeButton('删除条目',()=>{if(!confirm(`删除“${existing.title}”？`))return;try{const next=clone(A.data);next.documents=next.documents.filter(x=>x.id!==selected);next.nodes=next.nodes.filter(x=>x.id!==selected);A.validate(next);A.setData(next);editing=false;refresh();}catch(err){status('无法删除：'+err.message+'。请先移除相关关系。',true);}},'text-button'));form.append(buttons);form.onsubmit=e=>e.preventDefault();root.append(form);}
  function drawLabels(root){root.append(A.el('p','small','标签可新增、改名或删除。改名会同步修改使用该标签的条目；正在使用的标签不能直接删除。'));for(const [name,label]of Object.entries(tagFields)){const section=A.el('section','editor-label-group');section.append(A.el('h3','',label));const values=[...new Set([...A.arr(A.data.vocabulary[name]),...entries().flatMap(d=>A.arr(d[name]))])].filter(Boolean).sort();for(const value of values){const row=A.el('div','editor-list-item');row.append(A.el('span','',value),makeButton('改名',()=>{const newValue=prompt(`将“${value}”改名为：`,value)?.trim();if(!newValue||newValue===value)return;const next=clone(A.data);if(values.includes(newValue)){status('该分类中已存在同名标签。',true);return;}next.vocabulary[name]=A.arr(next.vocabulary[name]).map(x=>x===value?newValue:x);for(const d of [...next.documents,...next.nodes]){if(name==='type'){if(d.type===value)d.type=newValue;}else if(d[name])d[name]=A.arr(d[name]).map(x=>x===value?newValue:x);}A.setData(next);refresh();}),makeButton('删除',()=>{if(entries().some(d=>A.arr(d[name]).includes(value))){status('该标签仍被条目使用，请先修改条目。',true);return;}const next=clone(A.data);next.vocabulary[name]=A.arr(next.vocabulary[name]).filter(x=>x!==value);A.setData(next);refresh();},'text-button'));section.append(row);}const add=A.el('div','editor-row'),input=A.el('input');input.placeholder='新标签名称';input.setAttribute('aria-label',`新增${label}标签`);add.append(input,makeButton('添加',()=>{const value=input.value.trim();if(!value||values.includes(value)){status('请输入未使用的标签名称。',true);return;}const next=clone(A.data);next.vocabulary[name]=[...A.arr(next.vocabulary[name]),value];A.setData(next);refresh();}));section.append(add);root.append(section);}}
  async function publish(){const token=$('#github-token').value.trim();if(!token){status('请先输入 GitHub 授权令牌。',true);return;}const button=$('#publish-github');button.disabled=true;status('正在检查 GitHub 上的最新数据…');try{A.validate(A.data);const headers={Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'};const response=await fetch(`${api}?ref=main`,{headers,cache:'no-store'});if(!response.ok)throw new Error(`读取仓库失败（HTTP ${response.status}）`);const current=await response.json();const remote=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(current.content.replace(/\s/g,'')),c=>c.charCodeAt(0))));if(JSON.stringify(remote)!==JSON.stringify(baseline))throw new Error('仓库数据已在别处修改。请先导出草稿备份，再刷新页面并合并更改。');const bytes=new TextEncoder().encode(JSON.stringify(A.data,null,2)+'\n');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const put=await fetch(api,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({message:'Update atlas entries and category labels',content:btoa(binary),sha:current.sha,branch:'main'})});if(!put.ok){const detail=await put.json().catch(()=>({}));throw new Error(`发布失败（HTTP ${put.status}）：${detail.message||'请检查令牌权限'}`);}const result=await put.json();baseline=clone(A.data);localStorage.removeItem(key);$('#github-token').value='';$('#data-status').textContent='已发布到 GitHub · GitHub Pages 更新通常需要片刻';status(`发布成功！提交 ${result.commit.sha.slice(0,7)}。其他访客稍后即可看到更新。`);}catch(err){status(err.message||String(err),true);}finally{button.disabled=false;}}
  function init(){const button=$('#manage-button');button.onclick=()=>{$('#editor-dialog').showModal();draw();};$('#edit-entries-tab').onclick=()=>{tab='entries';editing=false;draw();};$('#edit-labels-tab').onclick=()=>{tab='labels';editing=false;draw();};$('#publish-github').onclick=publish;$('#discard-draft').onclick=()=>{localStorage.removeItem(key);A.setData(baseline);A.buildFilters();A.render();$('#total-count').textContent=String(A.records.length).padStart(2,'0');$('#data-status').textContent='已恢复线上知识库';editing=false;draw();status('未发布草稿已放弃。');};$('#download-json').onclick=()=>{const blob=new Blob([JSON.stringify(A.data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=A.el('a');a.href=url;a.download='knowledge-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#editor-dialog').addEventListener('close',()=>{$('#github-token').value='';});}
  function restore(){if(!A.data)return;baseline=clone(A.data);try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.data&&saved?.baseline){A.setData(saved.data);baseline=saved.baseline;A.buildFilters();A.render();$('#total-count').textContent=String(A.records.length).padStart(2,'0');$('#data-status').textContent='已恢复此浏览器中的未发布草稿';}}catch(err){status('草稿恢复失败：'+err.message,true);}}
  function imported(){draft();}
  return {init,restore,imported};
})();
