const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(read('js/core.js'),sandbox);const A=sandbox.window.Atlas;
const data=JSON.parse(read('data/knowledge.json'));A.setData(data);
assert.equal(A.byId.size,data.documents.length+data.nodes.length);
const html=read('index.html');
for(const match of html.matchAll(/(?:src|href)="([^"]+)"/g)){const ref=match[1];if(/^(?:#|data:|https?:)/.test(ref))continue;assert.ok(fs.existsSync(path.join(root,ref.split(/[?#]/)[0])),`Missing reference: ${ref}`);}
for(const file of fs.readdirSync(path.join(root,'js'))){new vm.Script(read('js/'+file),{filename:file});}
new vm.Script(read('data/knowledge-snapshot.js'));new vm.Script(read('assets/vendor/d3.v7.min.js'));
vm.runInContext(read('data/knowledge-snapshot.js'),sandbox);assert.equal(JSON.stringify(sandbox.window.ATLAS_SNAPSHOT),JSON.stringify(data),'Offline snapshot differs from JSON');
const clone=()=>JSON.parse(JSON.stringify(data));
let invalid=clone();invalid.documents.push(invalid.documents[0]);assert.throws(()=>A.validate(invalid),/重复 id/);
invalid=clone();invalid.documents[0].relations=[{target:'missing',type:'related_to'}];assert.throws(()=>A.validate(invalid),/目标不存在/);
invalid=clone();invalid.documents[0].year='invalid';assert.throws(()=>A.validate(invalid),/year/);
invalid=clone();invalid.documents[0].node_type=4;assert.throws(()=>A.validate(invalid),/node_type/);
invalid=clone();invalid.documents[0].document_nature='Charter';assert.throws(()=>A.validate(invalid),/文件性质/);
invalid=clone();invalid.documents[0].document_nature=['Charter','Charter'];assert.throws(()=>A.validate(invalid),/文件性质/);
invalid=clone();invalid.documents[0].document_nature=[''];assert.throws(()=>A.validate(invalid),/文件性质/);
A.validate([{id:'minimal',title:'Minimal record',year:2026}]);
invalid=clone();invalid.documents[0].topic_memberships=[{topic:'Imaginary topic',status:'source',evidence:'Test'}];assert.throws(()=>A.validate(invalid),/主题归属/);
invalid=clone();invalid.documents[0].topic_memberships.push({...invalid.documents[0].topic_memberships[0]});assert.throws(()=>A.validate(invalid),/重复/);
invalid=clone();invalid.documents[0].topic_memberships[0].status='source';delete invalid.documents[0].topic_memberships[0].location;assert.throws(()=>A.validate(invalid),/来源和位置/);
assert.equal(A.topicMemberships({timeline_topic:'Digital methods'})[0].status,'provisional','Legacy imports retain honest fallback');
assert.equal(A.topicMemberships(A.byId.get('delhi-declaration-2017')).length,4);
assert.equal(A.topicMemberships(A.byId.get('burra')).length,1,'Do not backdate later Burra provisions');
assert.ok(A.flowTopics.includes('Heritage visitation & tourism'));
assert.ok(A.flowTopics.indexOf('Heritage visitation & tourism')<A.flowTopics.indexOf('Digital methods'),'Visitation precedes digital methods in the reading order');
for(const id of ['gaze','tourism-charter-1999','tourism','ename','case-robben-island','case-tongariro','salalah-guidelines-2017','case-new-philadelphia-ar'])assert.ok(A.values(A.byId.get(id),'topic_memberships').includes('Heritage visitation & tourism'),`${id} has visitation membership`);
assert.equal(A.interpretiveSettings({})[0],'Unspecified / pending review','Old imports do not imply a setting');
assert.equal(A.byId.get('london-charter-2009').interpretive_setting[0],'Unspecified / pending review');
invalid=clone();invalid.documents[0].interpretive_setting='On-site';assert.throws(()=>A.validate(invalid),/阐释情境/);
invalid=clone();invalid.documents[0].interpretive_setting=['On-site','On-site'];assert.throws(()=>A.validate(invalid),/阐释情境/);
invalid=clone();invalid.documents[0].interpretive_setting_evidence={status:'source',evidence:'Test',source_url:'https://example.org'};assert.throws(()=>A.validate(invalid),/来源和位置/);
A.state.filters={interpretive_setting:new Set(['On-site'])};assert.ok(A.filtered().some(d=>d.id==='ename'),'Both matches on-site');assert.ok(A.filtered().some(d=>d.id==='case-new-philadelphia-ar'));assert.ok(!A.filtered().some(d=>d.id==='azuma-1997'));
A.state.filters={interpretive_setting:new Set(['Off-site'])};assert.ok(A.filtered().some(d=>d.id==='ename'),'Both matches off-site');assert.ok(!A.filtered().some(d=>d.id==='case-new-philadelphia-ar'));
A.state.filters={interpretive_setting:new Set(['On-site']),topic_memberships:new Set(['Digital methods'])};assert.ok(A.filtered().some(d=>d.id==='case-new-philadelphia-ar'));assert.ok(!A.filtered().some(d=>d.id==='london-charter-2009'),'General digital guidelines do not imply a setting');A.state.filters={};
A.state.filters={topic_memberships:new Set(['Digital methods'])};assert.ok(A.filtered().some(d=>d.id==='faro'));assert.ok(A.filtered().some(d=>d.id==='ename'));assert.ok(!A.filtered().some(d=>d.id==='tilden'));A.state.filters={};
A.state.query='Tilden';assert.deepEqual(Array.from(A.filtered(),d=>d.id),['tilden']);
A.state.query='';A.state.filters={type:new Set(['Book','Convention']),public_role:new Set(['Visitor'])};assert.equal(A.filtered().length,3,'OR within a field; AND across fields');
A.state.filters={};A.state.minYear='2005';A.state.maxYear='2006';assert.equal(A.filtered().length,3);
A.state.minYear='';A.state.maxYear='';A.state.filters={document_nature:new Set(['Guidelines'])};assert.deepEqual(Array.from(A.filtered(),d=>d.id).sort(),['intangible-sites-charter-2024','salalah-guidelines-2017']);
A.state.filters={document_nature:new Set(['Guidelines','Principles']),topic_memberships:new Set(['Digital methods'])};assert.deepEqual(Array.from(A.filtered(),d=>d.id),['seville-principles-2017'],'OR document forms; AND theme filter');
A.state.filters={};
A.state.query='no-such-entry';assert.equal(A.filtered().length,0);
assert.equal(A.safeURL('javascript:alert(1)'),null);
for(const d of data.documents){if(d.pdf&&!/^https?:/.test(d.pdf))assert.ok(fs.existsSync(path.join(root,d.pdf)),`Missing PDF ${d.pdf}`);}
console.log(`PASS: ${data.documents.length} entries, ${data.nodes.length} auxiliary nodes; JSON validation, references, script syntax, snapshot parity, search, compound filters, date range, empty results and unsafe URLs.`);
